spring.application.name=bairro

spring.datasource.url=jdbc:postgresql://localhost:5432/bairro
spring.datasource.username=bairro
spring.datasource.password=bairro123
spring.jpa.hibernate.ddl-auto=update
